### ISSUE TITLE
On selection of dates range is not applying for in and out dates....?

### ISSUE THREAD

**Issue by sachin499** [chronotruck/vue-ctk-date-time-picker#107]
Hello Developer,
I am v happy for having this plugin for my date picking. But my issue is i installed all dependencies required for ctkdatetimepicker widget also appeared on screen but while selecting date the dates and ranges are not applying....and adding v-model prop making it compiler error so i didn't included v-model prop....

one more thing i wanted to edit html of widget for some customization how can i achieve that

please sir guide me through the steps i will work on it..........

**Comment by LouisMazel** [comment]
Hi @sachin499,

Can you show me your code ? How you implement the component ? I'm not sure to understand you.

To customize, you can fork this repo.

**Comment by sachin499** [comment]
> Hi @sachin499,
> 
> Can you show me your code ? How you implement the component ? I'm not sure to understand you.
> 
> To customize, you can fork this repo.
/*this is how i imported in main.js*/
import VueCtkDateTimePicker from 'vue-ctk-date-time-picker';	
import 'vue-ctk-date-time-picker/dist/vue-ctk-date-time-picker.css';
/*this is the way i implemented code `*/
<vue-ctk-date-time-picker range-mode color="purple" format="YYYY-MM-DD" formatted="ddd D MMM YYYY" label="Select range"/>

**Comment by LouisMazel** [comment]
If you initialize the component just like that : 

```js
import VueCtkDateTimePicker from 'vue-ctk-date-time-picker';
import 'vue-ctk-date-time-picker/dist/vue-ctk-date-time-picker.css';
```

```html
<VueCtkDateTimePicker v-model="value">
```

`Value = null`

```js
new Vue({
        data () {
          return {
            value: null
          }
        }
      });
```

Normally, no prob with this config

**Comment by sachin499** [comment]
> If you initialize the component just like that :
> 
> ```js
> import VueCtkDateTimePicker from 'vue-ctk-date-time-picker';
> import 'vue-ctk-date-time-picker/dist/vue-ctk-date-time-picker.css';
> ```
> 
> ```
> <VueCtkDateTimePicker v-model="value">
> ```
> 
> `Value = null`
> 
> ```js
> new Vue({
>         data () {
>           return {
>             value: null
>           }
>         }
>       });
> ```
> 
> Normally, no prob with this config
Dear LouisMazel
Thank you very much it's working now, i didn't returned value prop to component instead i returned start and end date with typo errors so it didn't worked for me and one more thing is i want to edit html layout of widget how can i edit i mean in which file i searched by inspecting element also but i didn't found the way........

**Comment by LouisMazel** [comment]
Nice ! 

Sorry I can't help you to learn VueJs. You have many components to modify the layout

**Comment by sachin499** [comment]
> Nice !
> 
> Sorry I can't help you to learn VueJs. You have many components to modify the layout

It's ok LouisMazel i will try at my best thank you....
