### ISSUE TITLE
props onlyDate is invalid

### ISSUE THREAD

**Issue by panw3i** [chronotruck/vue-ctk-date-time-picker#109]
```js

 <vue-date-picker
              v-model="time"
              color = "#0382AA"
              locale="zh-cn"
              :dark="true"
              :onlyDate="true"
            />
```
still show this 
![image](https://user-images.githubusercontent.com/16938611/51156103-0c899080-18b5-11e9-93fa-1e3f0ec6f152.png)

**Comment by panw3i** [comment]
online  test  https://codepen.io/songyapan/pen/gZqdKO

**Comment by LouisMazel** [comment]
Hi @panw3i,

On your code pen it's the version 1.*
For this version follow this doc : https://github.com/chronotruck/vue-ctk-date-time-picker/blob/master/assets/doc-v1.md
Otherwise, update the component to 2.*

Thanks
