### ISSUE TITLE
Can not select date and time

### ISSUE THREAD

**Issue by jigneshwebclues** [chronotruck/vue-ctk-date-time-picker#11]
```
 <vue-ctk-date-time-picker
        v-model="value"
        :minute-interval="10"
        color="#96bf31"
        enable-button-validate
            without-input />
```

If i was used `without-input` that time i can see UI if was not used then i didn't see UI on click

**Comment by LouisMazel** [comment]
I'm not sure I understand what you mean.
You want to talk about the validation button that is not visible?

In this case, the validation button is hidden by default when you use the picker in inline mode (`without-input`). This button is useless in inline mode
