### ISSUE TITLE
applying Boolean option  props to component is confusing

### ISSUE THREAD

**Issue by sachin499** [chronotruck/vue-ctk-date-time-picker#112]
Don't know where i am doing wrong. but my aim is to disable noShortcuts option in rangemode i declaring it in prop and returning to component but not working....
`/* Component Code */
<VueCtkDateTimePicker v-model="value" range-mode color="#FF416C" formatted="ddd D MMM YYYY" v-bind:noShortcuts="noShortcuts" />
<script>
export default {
props: {
    noShortcuts:{
    type:Boolean, 
    default:true,
    },
  },
  data () {
    return {
      msg: 'Date Blockin Component',
      value:{
      start:'2019-01-17',
      end:'2019-01-20',
      },
    }
  },/*--here data ends--------*/
}
`

**Comment by LouisMazel** [comment]
Hi, 

Which version you use ?

**Comment by sachin499** [comment]
ాాాాాైాైాాైాిాైాిాైాిగా

**Comment by sachin499** [comment]
@

**Comment by sachin499** [comment]
I am using vue cli version  2 sir....

**Comment by LouisMazel** [comment]
@sachin499 

Version of VueCtkDateTimePicker sorry !

**Comment by sachin499** [comment]
The one you updated before date 18th of this month sir...

**Comment by LouisMazel** [comment]
For use the range mode, in version 2.* the props is `range` instead of `range-mode`

See the doc : https://github.com/chronotruck/vue-ctk-date-time-picker#readme

**Comment by sachin499** [comment]
Thank u mazel due to my healtg problem i didn't cheked mail, thanks for your response
