### ISSUE TITLE
[Feature Request] Button to clear input

### ISSUE THREAD

**Issue by jefflam** [chronotruck/vue-ctk-date-time-picker#115]
Thanks for the amazing library!

Would you have any tips or advice on what's the best way to add a button to clear the input/make it null?

Sure, I can do it on my own, but was wondering if there's a way to add a button to the widget, perhaps next to the 'Now' button, such that the date/time can be cleared when selected.

Thanks!

**Comment by airDjura** [comment]
I need that as well :) Good catch @jefflam

**Comment by MariaSMM** [comment]
All we need is this button!))

**Comment by LouisMazel** [comment]
🚀  #146 

![clear button feature](https://pouch.jumpshare.com/preview/PGODZ3TfHe2srVEVztBYiQAwY3a_HvrAyEZsCsEnrDqy3IXda4ZumVJwoG40hYCNZByuNLfd-mKWLrh60_e-MBA1jQB_zmxltR5bgJ1-nls)

You will can disable this feature with `no-clear-button` attribute

**Comment by LouisMazel** [comment]
It's released on 2.0.9 (https://github.com/chronotruck/vue-ctk-date-time-picker/releases/tag/2.0.9)

**Comment by airDjura** [comment]
@LouisMazel Great thanks :)
