### ISSUE TITLE
Huge (1.7M unpacked) size of main file

### ISSUE THREAD

**Issue by mankey-ru** [chronotruck/vue-ctk-date-time-picker#116]
dist/vue-ctk-date-time-picker.common.js size is 1704 kbytes, looks like something went wrong :)

**Comment by LouisMazel** [comment]
Hi @mankey-ru, 

Yes I know that and I want to resolve it soon ! 
You can see the build detail here : [https://github.com/chronotruck/vue-ctk-date-time-picker/blob/2.0.4/assets/report.html](https://github.com/chronotruck/vue-ctk-date-time-picker/blob/2.0.4/assets/report.html) (download and open it in your browser)

MomentJS (TimeZone & Range) is too big, solutions : 
- Use an other Date library
- Put MomentJS in 'peerDependencies' on `package.json`
- Just import the Moment JS parts we need
- Others !?

If you have the good solution, tell me ! :)

**Comment by LouisMazel** [comment]
I think I will remove support of time-zones : 

So I replaced `moment-timezone` dependency by `moment` and then the build look like :

| name | Size | Gzipped | 
|-------|-------|-------|
| dist/vue-ctk-date-time-picker.common.js | 766.28 KiB | 156.62 KiB |
| dist/vue-ctk-date-time-picker.umd.min.js | 335.06 KiB | 102.76 KiB |
| dist/vue-ctk-date-time-picker.umd.js | 766.69 KiB | 156.75 KiB |
| dist/vue-ctk-date-time-picker.css | 30.79 KiB | 4.34 KiB |

I will try to improve that again with the partial import of moment

PR : https://github.com/chronotruck/vue-ctk-date-time-picker/pull/117

**Comment by xxyuk** [comment]
Can't personally vouch for it but have read about `Day.Js` as an alternative

⏰ Day.js 2KB immutable date library alternative to Moment.js with the same modern API

https://github.com/iamkun/dayjs

reference: [moment/moment#2373 (comment)](https://github.com/moment/moment/issues/2373#issuecomment-406087130)
