### ISSUE TITLE
button without type is auto-submit form

### ISSUE THREAD

**Issue by miguelEsteban** [chronotruck/vue-ctk-date-time-picker#12]
You're using an HTML5 button element. This button has a default behavior of submit, as stated in the W3 specification as seen here: W3C HTML5 Button

So you need to specify its type explicitly:
`<button type="button">Button</button>`

Thanks.

**Comment by LouisMazel** [comment]
It's fixed in #13 
Package version : 1.1.19

Thanks for your feedback 👍
