### ISSUE TITLE
Input & Output data type of date ranges

### ISSUE THREAD

**Issue by m-mohr** [chronotruck/vue-ctk-date-time-picker#120]
Wonderful library, thanks. 

I use the date picker in range mode and try to figure out what the expected input and output of the value specified in v-model is. Personally, I expected it to be a two-element array, but it seems the output is an object with start and end properties. What do I need to pass? An object? A string separated with ' - '? The documentation doesn't mention anything regarding this.

Edit: Just found it in the demo. I think that information about the object with start and end properties for ranges should be added to the documentation. Thanks!

**Comment by LouisMazel** [comment]
Thanks for your feedback ! 

I will added this in the doc :)
