### ISSUE TITLE
[BUG] Date time picker eats all keyboard inputs

### ISSUE THREAD

**Issue by roidudev** [chronotruck/vue-ctk-date-time-picker#126]
Date time picker steals all keyboard presses and I cannot type into an input field on the same page.

**Steps to reproduce the behaviour:**
1. Add **inline** date time picker and text input field on a page
2. Try to use the text input
3. Date time picker eats the keyboard presses

**Expected behavior:**
Input field works normally.

**Desktop:**
 - OS: macOS Mojave 10.14
 - Browser: Chrome
 - Version: 72.0.3626.81

**Comment by knackjason** [comment]
I'm experiencing the same issue.

**Comment by theguywithglasses** [comment]
Same here. I'd vote for @knackjason solution too, namely, disable it completely when `inline` is used.

**Comment by knackjason** [comment]
@LouisMazel any thoughts here? This is a particularly annoying bug, so I think we'd all love for it to get squashed. :smile:

**Comment by easonclone** [comment]
Before bug fixes,not that I would recommend it, but if you really need it,
could use the `removeEventListener` to destroy.

```
  let el = this.$refs['date-time-picker'].$children[0].$children[0]
  window.removeEventListener('keydown', el.keyPressed)
```

**Comment by knackjason** [comment]
@easonclone thanks for the tip! I resorted to that hack while we wait for a better resolution. I did have to make one small change to get the right grandchild though:

```javascript
window.removeEventListener('keydown',   this.$refs['date-time-picker'].$children[0].$children[1]);
```

**Comment by zidworks** [comment]
Add this as a prop
:no-keyboard="true"

<VueCtkDateTimePicker
            :inline="true"
            :no-keyboard="true"
            v-model="model"
          />
