### ISSUE TITLE
[FEATURE REQUEST] Align the picker left or right. Make props position to also receive left or right.

### ISSUE THREAD

**Issue by Christhofernatalius** [chronotruck/vue-ctk-date-time-picker#130]
**Is your feature request related to a problem? Please describe.**
When the datepicker placed at the right side of the page, it will appear outside the page.
![Datepicker showing ](https://user-images.githubusercontent.com/13524958/53064786-9e5f6b80-34fb-11e9-82ad-3525515a42aa.png)

**Describe the solution you'd like**
Would be great if the props `position` can also receive `left` or `right` value, so that the date picker aligned left or right with the textbox.
So that the props `position `can be:
- `bottom left` (default)
- `bottom right`
- `top left`
- `top right`

**Describe alternatives you've considered**
Or maybe make a new props for horizontal align that only receive `left` or `right` value.

**Additional comment**
And also the documentation doesn't say what value is accepted for props `position`. I had to look inside the code to find that the position can only receive `bottom`, other value will behave like `top`.
Can you please add this to documentation?

**Comment by LouisMazel** [comment]
In next release, you can add `right` attribute !

**Comment by yashtatsme92** [comment]
> In next release, you can add `right` attribute !

Is there any PR associated with this enhancement request?

**Comment by christhofer** [comment]
> > In next release, you can add `right` attribute !
> 
> Is there any PR associated with this enhancement request?

It's already there in the props API.

**Comment by jmalczak** [comment]
I had the same issue, fixed it by adding a class `.header-datepicker-right` to datepicker and then overriding position for popup:

```
  .header-datepicker-right .datepicker {
    right: 0
  }
```
