### ISSUE TITLE
[BUG] Only-time formatted and format UI

### ISSUE THREAD

**Issue by xiopao** [chronotruck/vue-ctk-date-time-picker#134]
**Describe the bug**
The UI for the time picker is displaying with the format instead of the formatted.

**To Reproduce**
1. Set only-time="true"
2. Set format="HH:mm"
3. Set formatted="h:mm a"

**Expected behavior**
The UI for the time picker should display the "h:mm a" format

**Screenshots**
![screenshot from 2019-02-27 02-41-01](https://user-images.githubusercontent.com/11493204/53437771-4d8ace00-3a39-11e9-97ef-87df5187ae50.png)

**Comment by LouisMazel** [comment]
No it's not a bug : 

`format` attribut is for the UI 
`formatted` is the format of time output

Try : 

```
<VueCtkDateTimePicker
   v-model="yourValue"
   formatted="HH:mm"
   format="h:mm a"
   only-time
/>
```

**Comment by xiopao** [comment]
If this is not a bug then why is the display on my input "8:30 pm" but on the time picker it is "20:30"?

If I do it as you've said, it would display the time on the input as 20:30 and on the time picker as 8:30 pm, It should be the same, it would be confusing for the users if the picker is in HH:mm format but on the input it is in h:mm a format.

Also I still want my time to be on HH:mm format on v-model because that is the format on our database.

**Comment by xiopao** [comment]
I've found a solution, and this should be on the docs.

I used this settings:
`<VueCtkDateTimePicker
   v-model="yourValue"
   formatted="h:mm a"
   format="h:mm a"
   output-format="HH:mm"
   only-time
/>`

I hope this would help someone.

**Comment by ratribiana** [comment]
Yes it should be in the docs.. Thanks @xiopao it helps me a lot not searching for the answer and doing trial and errors
