### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by tonyfrenzy** [chronotruck/vue-ctk-date-time-picker#135]
**Description**
The minified .css file is missing thus causing compilation error.

The bug is basic, ```vue-ctk-date-time-picker*.min*.css``` is missing from the package's npm dist directory. 
```vue-ctk-date-time-picker.css``` is the only available CSS file and simply changing to that resolved the error.
Newbies will definitely get frustrated if they can't figure out what's happening under the hood.

**To Reproduce**
1. NPM Install: ```npm i --save vue-ctk-date-time-picker```
2. Import:
```
    - import VueCtkDateTimePicker from 'vue-ctk-date-time-picker';
    - import 'vue-ctk-date-time-picker/dist/vue-ctk-date-time-picker.min.css';
```
3. Compile: npm run dev or watch
...

**Expected behavior**
Compilation should go through successfully but threw up an error (in Laravel framework):
```
ERROR in ./resources/js/app.js
Module not found: Error: Can't resolve 'vue-ctk-date-time-picker/dist/vue-ctk-date-time-picker.min.css' in 'C:\x....
```

**Desktop (please complete the following information):**
 - OS: [Windows 10]

**Fix**
 - Add *vue-ctk-date-time-picker.min.css* to the dist folder
 - Or change the default *imported* css file to ```vue-ctk-date-time-picker.css```.

**Temporary Fix**
 - change ```vue-ctk-date-time-picker*.min.css*``` to ```vue-ctk-date-time-picker*.css*```

**Comment by LouisMazel** [comment]
Hi,

See the doc : https://github.com/chronotruck/vue-ctk-date-time-picker#es6-modules--commonjs

```js
import VueCtkDateTimePicker from 'vue-ctk-date-time-picker';
import 'vue-ctk-date-time-picker/dist/vue-ctk-date-time-picker.css';

Vue.component('VueCtkDateTimePicker', VueCtkDateTimePicker);
```

Never I ask to import the "min" version
