### ISSUE TITLE
Easy way to disable all past dates/times

### ISSUE THREAD

**Issue by shaunc869** [chronotruck/vue-ctk-date-time-picker#138]
Is there an easy way to disable all past dates/time combinations without creating an exhaustive array? Thanks!

**Comment by podhornyi** [comment]
You can specify 'min-date' parameter, fyi must be 'YYYY-MM-DD' format

**Comment by mapkbalaji** [comment]
I can specify the current date to be the min-date. What about time? I needed the current time to be the min time.

**Comment by podhornyi** [comment]
best way is to expand min-date parameter to allow both of next format:
YYYY-MM-DD
YYYY-MM-DD HH:MI

**Comment by podhornyi** [comment]
#144
