### ISSUE TITLE
Time picker does not parse time

### ISSUE THREAD

**Issue by etopian** [chronotruck/vue-ctk-date-time-picker#14]
When I add a date and time component the header for time picker shows the correct time, but the time picker always defaults to the current time instead of defaulting to the time from the model.

**Comment by LouisMazel** [comment]
Hi, 

When you use only the time-picker you must specify `time-format` :

```
         <ctk-date-time-picker
              v-model="yourValue"
              formatted="h:mm a"
              format="HH:mm"
              time-format="HH:mm a"
              label="Choose time"
              :minute-interval="10"
              disable-date
            />
```
formatted  : Format for input
format  : Format return by v-model
time-format : Format of time-picker 

In this example you have 3 different formats:
![Example](https://storage.jumpshare.com/preview/FTTjbooJtzH8L38fPSe9ZWrQhivjAlelHQ0_3vIIbDvvU9TdkjBgLJdc8eFDb51IQkzoJlNaj4cNWZJ_nozKhlNlSmh0egFbdyHzE6LvoMAI4av1wcwKsmUDuTGzHRrg)
