### ISSUE TITLE
Styles are completely destroyed on v2.1.0 [BUG]

### ISSUE THREAD

**Issue by AlejandroMut** [chronotruck/vue-ctk-date-time-picker#158]
Most styles for the calendar are destroyed on the new version (v2.1.0). Even on your Demo page.

![Screenshot_2019-04-22 vue-ctk-date-time-picker](https://user-images.githubusercontent.com/39420673/56513333-8ced0c80-6508-11e9-8c3c-c75230b34712.png)

**Comment by LouisMazel** [comment]
It's fixed on 2.1.1
