### ISSUE TITLE
Feature request: Support 24-hour time format

### ISSUE THREAD

**Issue by Sobient** [chronotruck/vue-ctk-date-time-picker#16]
It would be helpful to have the option to select the time using a 24-hour format.

**Comment by WilliamDASILVA** [comment]
@Sobient Depending to the locale you use, you'll have automatically the 12h or the 24 hour format. This could be a separate option in addition.

**Comment by LouisMazel** [comment]
Hi, 

Thanks @WilliamDASILVA ! 

The options : 

*formatted* : Format for input
*format* : Format return by v-model
*time-format* : Format of time-picker (use this only when you use the time-picker only)

**Comment by Christhofernatalius** [comment]
`time-format="H:mm"` works for me, and the list automatically changed to 0-23.

You should put this nice behavior in the documentation.

**Comment by LouisMazel** [comment]
Hi,

I released a beta version with some news features (2.0.0-rc5)
You can test it :
npm install vue-ctk-date-time-picker@beta
DEMO : https://htmlpreview.github.io/?https://github.com/chronotruck/vue-ctk-date-time-picker/blob/feature/refont/demo/index.html
DOC : https://github.com/chronotruck/vue-ctk-date-time-picker/blob/feature/refont/README.md

Le me know if you have others feedbacks (events, bugs, etc)

Thanks

**Comment by Christhofernatalius** [comment]
@LouisMazel v2 seems very promising

I really like the new custom-shortcuts, and the event spi. There is typo "Component is destoyr"

btw, I can't access the demo page though, it just showing Loading...

**Comment by Christhofernatalius** [comment]
Hey @LouisMazel , I upgraded to v2.0.3, and now the time picker reverted back to 12h format. And seems like there is no props `time-format` anymore.
How to make the time picker use 24h format?

Changed locale and timezone but the timepicker still in 12h format.

**Comment by Christhofernatalius** [comment]
With v2, there is no `time-format` anymore
Use `format='YYYY-MM-DD HH:mm'`

**Comment by habib-ch** [comment]
`format="YYYY-MM-DD HH:mm"`

Above thing worked for me.
