### ISSUE TITLE
[BUG] Initial formatted value is using the wrong locale

### ISSUE THREAD

**Issue by joel-ns** [chronotruck/vue-ctk-date-time-picker#160]
**Describe the bug**
The formatted value in the custom input is rendered with default locale despite setting the locale property. In my specific case, the default locale is "en" and I create the component with locale set to "sv". The custom input is still rendered in English the first time I view the component.

**To Reproduce**
1. Set property "locale" to something else than the default locale. Also set the initial value
2. Render component, custom input is rendered with default locale
3. Open calender and select any other value
4. Now the custom input component is correctly rendered with the provided locale

**Expected behavior**
The initial formatted value should use the locale set in the locale-property.

**Screenshots**
![Peek 2019-04-29 15-02](https://user-images.githubusercontent.com/23070625/56895061-8292bb80-6a90-11e9-8b0b-efb8ed7989d8.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04 LTS
 - Browser Firefox
 - Version 66.0.3

**Additional context**
Link to reproduce bug: https://codepen.io/anon/pen/BEEjry

**Comment by erubielgzz** [comment]
Had the same problem, 
If you want to force the plugin to some locale you could do something like this:

1. Download the source from the repo
2. Edit util.js and force your locale like I do in this snippet:

```
import moment from 'moment'

export const getDefaultLocale = () => {
  if (typeof window === 'undefined') return null

  // const { userLanguage, language } = window.navigator
  const locale = ('es').substr(0, 2)
  moment.locale(locale)
  return locale
}
```

3 . npm run build 
4. Use the dist files instead of installing via npm.
