### ISSUE TITLE
How to detect on-change?

### ISSUE THREAD

**Issue by rehmatworks** [chronotruck/vue-ctk-date-time-picker#169]
How to listen for on-change event? I want to run a method if a new date is selected. No documentation for this on official website or here. Any help is appreciated.

**Comment by haringsrob** [comment]
You could just watch the v-model property?

```
        watch: {
            dates: function (val) {
                this.datesOk = !!(val.start && val.end) && this.dates.start !== this.dates.end;
            },
}
```

**Comment by WilliamDASILVA** [comment]
Hello,
In addition to @haringsrob 's message, the datepicker emits the following events if needed:
- validate
- input
- formatted-value
- destroy
- is-shown
- is-hidden

(https://github.com/chronotruck/vue-ctk-date-time-picker#events-api)

**Comment by ijunaid8989** [comment]
do the v-model's value got to change if you have a validate button without pressing it to value never changes.
