### ISSUE TITLE
Your package is AWESOME!!

### ISSUE THREAD

**Issue by nicolasvahidzein** [chronotruck/vue-ctk-date-time-picker#177]
Just wanted to tell you i loved your package!!!

This is some grade A awesomeness. Thank you dear sir.

**Comment by siegelion** [comment]
I agree

**Comment by Matthew-J-Spencer** [comment]
So much better than the top starred vue datepicker library. Thanks for this!

**Comment by WilliamDASILVA** [comment]
On the behalf of the original author @LouisMazel and Chronotruck, thank you for your kind words! ❤️
