### ISSUE TITLE
unable to set Dynamic Mindate and Maxdate

### ISSUE THREAD

**Issue by abhiramkalagarla** [chronotruck/vue-ctk-date-time-picker#18]
Unable to set Dynamic mindate and maxdate with the model change

<vue-ctk-date-time-picker min-date="'minrecoverydate'" max-date="'maxrecoverydate'" v-model="Datetime" formatted= 'YYYY-MM-DD HH:mm:SS'> </vue-ctk-date-time-picker>

**Comment by LouisMazel** [comment]
Hi, 

I'm not sure I understand. Have you an example of code ? 

minDate & maxDate are really a reactive values : 
[minDate maxDate](https://jumpshare.com/v/AY1v7dhMHrlW5JbVkZtP)
