### ISSUE TITLE
[FEATURE REQUEST] No name prop

### ISSUE THREAD

**Issue by kaznache** [chronotruck/vue-ctk-date-time-picker#181]
Hi! Can you add prop name directly into input please?

It would be usefull for forms after submit

**Comment by WilliamDASILVA** [comment]
Hello !

Thank you for taking the time to write this issue. Indeed that's something quite important, even for accessibility & validation issues.

I'm not sure that a `prop` for this is would be necessary, we could just pass the attribute to the child component using `$attrs.name`.

**Comment by khaledelmahdi** [comment]
Hi,

I am also interested on having a name property, how to use `$attrs.name` you've mentioned above?
