### ISSUE TITLE
input element and wrapper div have same id.

### ISSUE THREAD

**Issue by muschottkey** [chronotruck/vue-ctk-date-time-picker#184]
**Describe the bug**
The `div` that wraps the date picker elements, as well as the `input` element for the date picker, both have the same `id`. Consider the following code:

```js
<div
    :id="id"
    ref="parent"
    v-click-outside="() => { toggleDatePicker(false) }"
    class="date-time-picker"
  >
    <CustomInput
      v-if="hasInput"
      :id="id"
      ref="custom-input"
      ...
```

You can observe that the `div` and the `CustomInput` have the same parameter for `id` prop/attribute. In `CustomInput`, we use the prop directly to set the id of the input like

```js
<input
    :id="id"
    ...
```

### The problem

`id` **attribute is supposed to be unique, so that it uniquely identifies an element in the DOM tree**. Having an `id` attribute being shared means that any events or listeners that target an element using the `id` will **only be registered to the first element** that had that id.

In this case, the `div` element is first, which means that it will be the target of any events that target the value of `id` prop.

This affects form labels because labels are associated with their respective form element using a `for` attribute which represents the `id` of the input element they are tied to. Clicking on the label causes the form to automatically focus on the element. This is also used in assistive technologies to provide better user experience by establishing relationships between visible elements (labels) and the input elements they represent.

**To Reproduce**
1. Create any datepicker instance with an `id` parameter provided.
2. Inspect the DOM or run `document.getElementById(your-id)` and check if the node returned represents an `input` or the `div` wrapper.
3. Inspect the DOM to see if the wrapper `div` and `input` nodes share the same **id**.

**Expected behavior**
The `id` prop should be used only to assign an id to the `input` element itself without any modification. The `div` should get a computed `id` based on the `id` I've defined, e.g. a computed id like 

```js
<div 
    :id="`${id}-wrapper`"
    ...
```

By implementing the code that way, I will be able to consistently target the wrapper div if I want to because I can tell what id it will always have, and I will be able to link a form `label` element to the `datepicker` so that screenreaders can understand the relationship between these two, and so that when I click on the label, the datepicker gets focused on.

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: Any
 - Version: Any

**Smartphone (please complete the following information):**
 - Device: Any
 - OS: Any
 - Browser: Any
 - Version: Any

**Additional context**
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#Attributes

**Comment by WilliamDASILVA** [comment]
Thank you for taking the time to write this issue. Having multiple elements with the same `id` is indeed not a wanted behaviour. I'll take a look very soon to it.
Any PRs are also welcome! 😄

**Comment by alemagio** [comment]
I can i work on this?

**Comment by alemagio** [comment]
#205
