### ISSUE TITLE
Submit button is cut off on small screens (iPhone5 SE) [BUG]

### ISSUE THREAD

**Issue by jkndrkn** [chronotruck/vue-ctk-date-time-picker#192]
Have really been enjoying using this datepicker. Nice work!

Running into an issue that is making it unusable on small screens (iPhone5 SE).

When opening the date picker on Safari on iPhone5 SE with iOS 12.3.1, the submit button (green checkmark) is cut off. See screenshot.

I have tried using padding or margin to bring the buttons farther into the viewport, but this stretches out the layout for the entire page.

![IMG_6706](https://user-images.githubusercontent.com/91959/62068261-bacaa700-b203-11e9-9700-b5ca1c7bf730.jpg)

**Comment by jkndrkn** [comment]
I noticed that I was using the following META tag settings:
    `<meta name="viewport" content="width=device-width,initial-scale=1.0">`

Adding user-scalable=no fixed the issue:
    `<meta name="viewport" content="width=device-width,initial-scale=1.0,user-scalable=no">`

See: https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariHTMLRef/Articles/MetaTags.html

**Comment by WilliamDASILVA** [comment]
Hello,

Thank you for reporting this issue!
Indeed I achieved to reproduce this issue. Adding it to the `v2.4.0` milestone for monday.

**Comment by Sethles** [comment]
![image](https://user-images.githubusercontent.com/12828824/77840463-22b50100-7188-11ea-858a-7891de51a1ce.png)

Same for me.

**Comment by WilliamDASILVA** [comment]
Fixed in https://github.com/chronotruck/vue-ctk-date-time-picker/pull/299
