### ISSUE TITLE
Allow support for external class props

### ISSUE THREAD

**Issue by vikrampariharcodereadr** [chronotruck/vue-ctk-date-time-picker#193]
Hi It will be more flexible if you can add class props support like
`<date-time-picker v-model="startDate" :format="datePickerOptions_" :class="myexternalclass"></date-time-picker>`

**Comment by WilliamDASILVA** [comment]
Hello,

Thank you for taking the time to make this issue. I think you're trying to customize the calendar but struggle with the current classes? If so, I'm considering this as duplicate of #149 .
Poke me if I'm wrong.
