### ISSUE TITLE
[BUG] YYYY MM DD HH:mm  Format not wroking

### ISSUE THREAD

**Issue by vikrampariharcodereadr** [chronotruck/vue-ctk-date-time-picker#194]
Hello I have replace bootstrap datepicker with this given component.

But there are some bug which i not suppose to resolved.
I am using component in this format
`                      <date-time-picker v-model="startDate" :format="YYYY-MM-DD LT" :output-format="YYYY-MM-DD LT" no-button="true" label="  Start date" no-header="true" input-size="sm"></date-time-picker>`

![Screenshot from 2019-07-31 17-50-44](https://user-images.githubusercontent.com/46337013/62211382-e98b7d80-b3bb-11e9-9269-c3f6ea925f7c.png)

See the image 
"From section is " vue-ctk-date-time-picker component
"To section is " bootstrap vue datepicker.`

So vue-ctk-date-time-picker component date display should be like as bootstrap vue datepicker.

Thank you.

**Comment by Thorazine** [comment]
You are missing some quotes around your format, but I can confirm this bug.

https://codepen.io/anon/pen/BXYWqd

**Comment by WilliamDASILVA** [comment]
Cannot find any issues here. As @Thorazine said, the `format` property formats the returning value.
Example:
```<vue-ctk... format="YYYY" v-model="value">```
