### ISSUE TITLE
[BUG] "Invalid date" when clicking "PM" twice

### ISSUE THREAD

**Issue by NicksonYap** [chronotruck/vue-ctk-date-time-picker#196]
**Describe the bug**

When using 12-hour time, clicking 'PM' button the second time consistently outputs 'Invalid date' (moment.js to fails to parse the time.)

clicking 'AM' multiple times works fine

Related to: https://github.com/chronotruck/vue-ctk-date-time-picker/issues/179

**Expected behavior**
Since clicking 'AM' multiple times intentionally makes the hour jump to 1 and 12 and vice versa

I suppose 'PM' should react that way too, instead of producing 'Invalid date'

**Screenshots**

![image](https://user-images.githubusercontent.com/5380731/62417457-5d5eac00-b682-11e9-9a2c-6448d7b5a85c.png)

![image](https://user-images.githubusercontent.com/5380731/62417460-6485ba00-b682-11e9-89e3-2cffe7fb8ecc.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version release 2.1.1

**Comment by Tiarhai** [comment]
@NicksonYap 

Created a pull request with this bug fixed.

"Expected Behaviour" is different than suggested here. Instead of changing the time +/- 12 hours, we now simply don't make any changes to the time values when AM or PM is clicked more than once.

**Comment by NicksonYap** [comment]
@Tiarhai 
Awesome!
I do agree, it can be a bit confusing if it changes the time if AM/PM clicked more than once.
But I'm pretty sure there was a reason for that, probably for convenience?
I'm fine with both :P 
Although not sure if it's considered a breaking change

We'll let the author to decide the PR

**Comment by NicksonYap** [comment]
closed by accident, still pending author response

**Comment by Tiarhai** [comment]
@NicksonYap The PR with a fix to this was merged 2 weeks ago if you would like to close the issue :+1: :smile:

**Comment by NicksonYap** [comment]
Ah, wasn't aware
Is it in release?

**Comment by Tiarhai** [comment]
Oh, no there has not been a new release yet. Also, the latest Github release and npm versions are different.

**Comment by nikkanetiya** [comment]
@Tiarhai I think it is still happening in the newer version as well. We can see it in the demo as well as we are using it in our project. Everything is working fine except that Invalid date sometime. Thanks for your time & effort to maintain this package.

**Comment by Tiarhai** [comment]
@nikkanetiya Yeah the PR has been accepted, but a new version still hasn't been released yet.

To get the latest changes yourself, you can clone this repo, `npm run build` and then copy the compiled .js files from the `dist` folder into your project. Although it's not ideal, it is the only way to apply the fix until a new version is published.

**Comment by nikkanetiya** [comment]
@Tiarhai Thanks for replay. Any ETA for that release? We are using it widely in our project.

**Comment by WilliamDASILVA** [comment]
@nikkanetiya @Tiarhai 

This fix has been released in the version [v2.2.0](https://github.com/chronotruck/vue-ctk-date-time-picker/releases/tag/2.2.0).
Thanks for your help!

**Comment by rodrigogs** [comment]
It's happening to me on 2.5.0
