### ISSUE TITLE
[BUG] Component emits is-hidden on every click out of component

### ISSUE THREAD

**Issue by NikoFoX** [chronotruck/vue-ctk-date-time-picker#197]
**Describe the bug**
Component emits is-hidden on every click out of component. This not only litters the events' list, but also makes emit useless with 2+ components on the same view.

**To Reproduce**
1. Place 2 VueCtkDateTimePicker components on the same view.
2. Click anywhere outside of the component.
3. See 2 is-hidden emits on the Events tab in Vue Devtools or any other method to watch the emits.

**Expected behavior**
Is-hidden emit should be thrown out only when you close the component's picker.

**Screenshots**
![vuectkdatetimepicker_double_emits](https://user-images.githubusercontent.com/10162667/62701640-1ad00300-b9e5-11e9-9b62-14c0acf60af9.png)

**Desktop (please complete the following information):**
 - Ubuntu 18.04
 - Chrome, Firefox

**Comment by cmendez2121** [comment]
inside   

`__toggleDatePicker:_ function toggleDatePicker(val) {_`

changed 
    	
      _if (this.disabled) return;
      var isOpen = val === false || val === true ? val : !this.pickerOpen;_

for 

      _if (this.disabled) return;
      if (this.pickerOpen==false && val==false){ return; }
      var isOpen = val === false || val === true ? val : !this.pickerOpen;_

and so far that solved the problem on my side/code,  hope this helps someone else.

Also another Issue i see using Multiple instances / arrays etc.. 
Is that there is no way to know which instance/control is launching the event so far i have to make some mods on the code  and on every $emit the control launches i added  ", this.id " or  " _vm.id" 
cause i needed to control each value on the array and also validate element dates/ranges vs other array elements/values/ranges.

**Comment by leesunghak** [comment]
@cmendez2121 This fixed my issue with is-hidden emit triggered on background click. Thanks. Wonder if there's more permanent solution though?

**Comment by WilliamDASILVA** [comment]
Hello @NikoFoX 
Thank you for reporting this issue. It's indeed *not a wanted* behavior!

**Comment by WilliamDASILVA** [comment]
Hello,
This bug is now solved under the v2.3.0 tag.
