### ISSUE TITLE
[FEATURE REQUEST] Function callbacks for custom-shortcuts?

### ISSUE THREAD

**Issue by NicksonYap** [chronotruck/vue-ctk-date-time-picker#218]
Hi There~

Currently Custom-Shortcuts aren't as custom as it can be, as it seems to only work relative to "now" / "today"

It would be great to allow shortcuts to simply act as a button to trigger a function / callback expecting time to be returned

For example:

```js
[
  { label: `Aujourd'hui`, value: 'day', isSelected: false },
  { label: 'Yesterday', value: '-day', isSelected: false },
  ...
  { label: 'Start Of Day', callback: setStartOfDay, isSelected: false },
  { label: '2019 Valentines Day', callback: setValentinesDay, isSelected: false },
];

```

```js
setStartOfDay(value) {
  return moment(value).startOf('day').toString()
}

setValentinesDay(value) {
  return "2019-02-14"
}

```

This way we can do any kind of shortcut that we want, while enjoying the convenience of the current implementation

P.S (it's true I just wanted a button in the calendar, and shortcuts seems to be the perfect location)

I'm willing to contribute but quite confused with the NPM workflow, and don't actually know how to manage my own development version while using releases

Thanks!

**Comment by WilliamDASILVA** [comment]
Hello,

Thanks for opening this issue. That would be a nice-to-have feature with the rework I've made recently (breaking change) in the range shortcut.
Adding this to the `v2.4.0` milestone for monday.

**Comment by NicksonYap** [comment]
Awesome!

> That would be a nice-to-have feature ...

It's a **very** nice to have btw :P
