### ISSUE TITLE
Conflicts with jQuery UI

### ISSUE THREAD

**Issue by 181** [chronotruck/vue-ctk-date-time-picker#219]
**Describe the bug**

**Steps to reproduce**
Describe us how we could reproduce the bug you're trying to report.

Example:

**Expected behavior**
A clear and concise description of what you expected to happen when you encounter the bug.

**Screenshots**

**Device (please complete the following information):**

 -OS: [e.g. iOS, Windows 10, ...]
 -Browser: [e.g. Chrome 75, Safari 9]
 -Package version: [e.g. 2.2.0]

**Additional context**

**Comment by WilliamDASILVA** [comment]
Hello,
Please follow the issue template. You're not giving any information here.
Will re-open when more informations will be provided!

Thanks 😃
