### ISSUE TITLE
[ENHANCEMENT]Range with time

### ISSUE THREAD

**Issue by svarughese91** [chronotruck/vue-ctk-date-time-picker#224]
I would like to create a range which works now but choose a specific time for that as well.  So by default now its all day for the range, I would like to choose a time like 9:00 AM Wednesday, October 2 - 6:00 PM Thursday, October 3

**Comment by honsa** [comment]
There is already an issue for this:

https://github.com/chronotruck/vue-ctk-date-time-picker/issues/176

**Comment by WilliamDASILVA** [comment]
Hello,

Thanks for your interest in this feature. Indeed there is already an issue for that. FYI, I'm adding this to the v2.4.0 milestone for monday.
