### ISSUE TITLE
Expose date-time lib

### ISSUE THREAD

**Issue by webbby** [chronotruck/vue-ctk-date-time-picker#226]
I see that you are using `moment` as date-time library.
Could you expose it so that the user is able to parse, format ... handle dates in general without adding another lib.
For instance I have to move between a few date formats so if I am able to use the already imported moment lib would be great 10x.

**Comment by WilliamDASILVA** [comment]
Hello!

Thank you for taking the time to make this issue. Currently `moment` is used in may places, even to handle the calendar formatting itself so I'm not totally sure if that would even be possible...
I'm closing this issue for now but keeping it in the back of my head.
