### ISSUE TITLE
Unable to select time on mobile devices

### ISSUE THREAD

**Issue by SouthRibbleTech** [chronotruck/vue-ctk-date-time-picker#229]
**Describe the bug**
on a mobile device, the option to select the time is not shown.

**Steps to reproduce**
Open the calendar on a small screen device.

Example:

**Expected behavior**
Should be able to change the time on a mobile device.

**Screenshots**

**Device (please complete the following information):**

 -OS: Android Samsung S10+
 -Browser: Chrome when using developer tools in mobile mode.

**Comment by mludi** [comment]
Any news on that? I've the same issue.

**Comment by AmitVSH** [comment]
Same here... unable to find the solution.

**Comment by WilliamDASILVA** [comment]
Hello,

Thank you for taking the time by making this issue.
That's indeed an important bug that should be fixed asap.

**Comment by raloeasy** [comment]
Any news? I have the same issue. Thanks

**Comment by raloeasy** [comment]
I have found a workaround. If i delete all media queries in the css file it works fine and is accessible from mobile phone correctly.

**Comment by jbardnz** [comment]
Any update on this issue, right now this plugin is unusable on mobile due to this issue.

**Comment by mjackz** [comment]
As a workaround added some css to adjust the height of the calendar

@media screen and (max-width: 415px) {
   .pickers-container { height: 100%;   }  /* optional: move accept button at bottom of screen */
   .time-picker { max-height: 200px;   }
}

**Comment by edgarsn** [comment]
Looks like this package is not maintained anymore. :(

**Comment by Bhavna2207** [comment]
Hey, any update on this? I am facing the same issue, even if I give a definite height it still doesn't show up and if in case it is visible I am not able to scroll or do anything.

**Comment by WilliamDASILVA** [comment]
Fixed in https://github.com/chronotruck/vue-ctk-date-time-picker/pull/299

**Comment by fawel11** [comment]
This code worked for me.
@media screen and (max-width: 415px) {
.pickers-container { height: 100%; } /* optional: move accept button at bottom of screen */
.time-picker { max-height: 200px; }
}
