### ISSUE TITLE
If you have 2 components next to each other does not click on the right one properly

### ISSUE THREAD

**Issue by svarughesehcl** [chronotruck/vue-ctk-date-time-picker#249]
**Describe the bug**
I have 2 date-time-pickers next to each other:
```
      <tbody>
        <tr>
          <td>
            <input class="newScanInput" v-model="newScan.scanId" placeholder="scanId" />
          </td>
          <td>
            <VueCtkDateTimePicker
              v-model="newScan.start_scan_window"
              :dark="true"
              :format="'MM/DD/YYYY HH:mm'"
            />
          </td>
          <td>
            <VueCtkDateTimePicker
              v-model="newScan.end_scan_window"
              :dark="true"
              :format="'MM/DD/YYYY HH:mm'"
            />
          </td>
        </tr>
      </tbody>
```

When I click on the 2nd one it clicks on the first component even though I am clicking on the second one.  I have to click on the extreme left end side of the component for the second one to be clicked

**Steps to reproduce**
Describe us how we could reproduce the bug you're trying to report.

```
      <tbody>
        <tr>
          <td>
            <input class="newScanInput" v-model="newScan.scanId" placeholder="scanId" />
          </td>
          <td>
            <VueCtkDateTimePicker
              v-model="newScan.start_scan_window"
              :dark="true"
              :format="'MM/DD/YYYY HH:mm'"
            />
          </td>
          <td>
            <VueCtkDateTimePicker
              v-model="newScan.end_scan_window"
              :dark="true"
              :format="'MM/DD/YYYY HH:mm'"
            />
          </td>
        </tr>
      </tbody>
```

**Expected behavior**
When i click on the first component the first one should be selected.  When I click on the second one should be clicked.

**Screenshots**
<img width="801" alt="Screen Shot 2019-11-14 at 2 31 34 PM" src="https://user-images.githubusercontent.com/36015195/68889912-e0fd4f80-06eb-11ea-9d76-4f4a619ed76f.png">
<img width="758" alt="Screen Shot 2019-11-14 at 2 31 09 PM" src="https://user-images.githubusercontent.com/36015195/68889919-e490d680-06eb-11ea-9073-b52ef765c956.png">

**Device (please complete the following information):**

 -OS: Mac 10.14.6
 -Browser: electron
 -Package version: 2.3.0

**Comment by carterbourette** [comment]
@svarughesehcl it would appear that by default the id is set to `datepicker-input`.

I resolved the issue by passing a value into the id prop.

Example:
```
      <tbody>
        <tr>
          <td>
            <input class="newScanInput" v-model="newScan.scanId" placeholder="scanId" />
          </td>
          <td>
            <VueCtkDateTimePicker
              v-model="newScan.start_scan_window"
              :dark="true"
              :format="'MM/DD/YYYY HH:mm'"
              id="start_scan"
            />
          </td>
          <td>
            <VueCtkDateTimePicker
              v-model="newScan.end_scan_window"
              :dark="true"
              :format="'MM/DD/YYYY HH:mm'"
              id="end_scan"
            />
          </td>
        </tr>
      </tbody>
```

**Comment by svarughesehcl** [comment]
@carterbourette this worked!  Thanks so much for your help!
