### ISSUE TITLE
Month and year label bug on IE11

### ISSUE THREAD

**Issue by Epistol** [chronotruck/vue-ctk-date-time-picker#267]
**Describe the bug**
The month and year label are shown for just a letter, the width is completely bugged.

**Steps to reproduce**
Open a datepicker on ie11.

Example:

https://chronotruck.github.io/vue-ctk-date-time-picker/

**Screenshots**
![2020-02-03 10_26_00-Window](https://user-images.githubusercontent.com/6005885/73641155-dfe71900-466f-11ea-87b5-79dc9bb197dc.png)

**Comment by garamon** [comment]
Try the following code. In my case, it's working fine.
```
<style lang="scss">
.date-time-picker {
  .flex-1 {
    -webkit-box-flex: 1;
    -moz-flex: 1;
    -ms-flex: 1;
    flex: 1 0 auto;
  }
}
</style>

```
