### ISSUE TITLE
The latest versions in Github and npm are different

### ISSUE THREAD

**Issue by mikinovation** [chronotruck/vue-ctk-date-time-picker#288]
vue-ctk-date-time-picker doesn't work in production env and the UI is collapsed.

I checked our package.json and the vue-ctk-date-time-picker version.

It's like this

```
"vue-ctk-date-time-picker": "^2.4.0",
```

in Github

![FireShot Capture 114 - Releases · chronotruck_vue-ctk-date-time-picker - github com](https://user-images.githubusercontent.com/33025073/80774401-e403d380-8b97-11ea-86c8-1a5702f31ba9.png)

but in npm

![FireShot Capture 115 - vue-ctk-date-time-picker - npm - www npmjs com](https://user-images.githubusercontent.com/33025073/80774552-5674b380-8b98-11ea-9876-b8278673aa12.png)

Did you delete the tag "v2.4.0" in Github after release?

Please check it. Thank you

**Comment by WilliamDASILVA** [comment]
Hello,

Thank you for taking the time to open this issue.
Indeed I forgot to push the tag to Github when i published the npm package.

I'll be more careful in the next releases.
