### ISSUE TITLE
Disabled property doesn't disable 'clear' button

### ISSUE THREAD

**Issue by rodrigoabb** [chronotruck/vue-ctk-date-time-picker#289]
Hi, first of all, thanks for this brilliant component, it's amazign!

Here's the description of what was found:

**Describe the bug**
When setting 'disable' property on, clear button is still clickable.

**Steps to reproduce**
- Go to this demo: https://chronotruck.github.io/vue-ctk-date-time-picker/
- Go to the 'Disabled Picker' example
- Open Edit Options
- Disable 'disabled' property
- Pick a datetime
- See how clear button shows up (expected as noClearButton is disabled)
- Enable 'disabled' property
- See how the whole item is disabled. but clear button is still there and it's clickable

**Expected behavior**
If it appears, when 'disabled' property is set to true, clear button should be disable as well, or not show up

**Device (please complete the following information):**

 -OS: Linux Mint
 -Browser: Chrome 80

Thanks!!

**Comment by WilliamDASILVA** [comment]
Hello,

Thank you for taking the time to open this issue.
It's indeed not a wanted behaviour. Fixing this.
