### ISSUE TITLE
end date with min date until am does not show pm option

### ISSUE THREAD

**Issue by shidcordero** [chronotruck/vue-ctk-date-time-picker#295]
**Describe the bug**
I have a start date and end date. The end date has a min date of start date + 1 day. Now when I set the start date at AM time for example 04/06/2020 11:30am, I cannot see the PM options in my end date.

for Start Date
`
                    <VueCtkDateTimePicker
                      id="startDate"
                      v-model="$v.startDate.$model"
                      no-label
                      formatted="DD/MM/YYYY hh:mm a"
                      label="dd/MM/yyyy hh:mm am/pm"
                      input-size="lg"
                      :disabled="saving"
                      :error="$v.startDate.$dirty && $v.startDate.$invalid"
                    ></VueCtkDateTimePicker>`

for End Date
`<VueCtkDateTimePicker
id="endDate"
                      v-model="$v.endDate.$model"
                      no-label
                      formatted="DD/MM/YYYY hh:mm a"
                      label="dd/MM/yyyy hh:mm am/pm"
                      input-size="lg"
                      :disabled="saving"
                      :error="$v.endDate.$dirty && $v.endDate.$invalid"
                      :min-date="minEndDate"
                    ></VueCtkDateTimePicker>`

and minDate is just 
    `minEndDate() {
      return moment(this.$v.startDate.$model)
        .add(1, 'days')
        .format()
    }
`

**Expected behavior**
Expected behavior would be I can see the PM option

**Screenshots**

![image](https://user-images.githubusercontent.com/26376208/83710734-fc15b980-a653-11ea-95ac-aa60f29dcb53.png)

**Device (please complete the following information):**

 -OS:  Windows 10
 -Browser: Chrome and Edge
 -Package version: latest

**Comment by jtylock** [comment]
@WilliamDASILVA Thank you for fixing this issue!  However there is still a small bug where the minutes of the min date in the PM hour are disabled like the AM hour. For example, if min date is 6/30/20 11:25 AM, then before that time is correctly disabled but 6/30/20 11:00 - 11:25 PM minutes are incorrectly disabled.

**Comment by shidcordero** [comment]
@WilliamDASILVA  The bug was fixed but another issue occurs where in if I have a start date for example 07/18/2020 at 12:00 AM, I cannot set the hour as it was disabled 
![image](https://user-images.githubusercontent.com/26376208/87755680-0376d800-c83a-11ea-8f38-ea8982a56aea.png)
