### ISSUE TITLE
Range mode with disabled dates

### ISSUE THREAD

**Issue by slevinsk21** [chronotruck/vue-ctk-date-time-picker#44]
**Range mode with disabled dates**

Hello, I'm trying to integrate the directive of  "Disabled-dates " that allows an array with the days I want to block but when I use the  "range-mode " This does not work, I was checking the code and it seems that if there is functionality. Will it be due to a bug that does not take the array of dates to disable it? Thanks for your response in advance, the component is fantastic continues to improve

**Comment by LouisMazel** [comment]
Hi @slevinsk21,

Thanks so much for you feedback !! 
"Disabled dates" issue with range mode is fixed on this PR #47 

I release soon (1.3.2)
