### ISSUE TITLE
[Accessibility] DateTimePicker is not keyboard accessible

### ISSUE THREAD

**Issue by abhipanda** [chronotruck/vue-ctk-date-time-picker#45]
Example: http://www.oaa-accessibility.org/examplep/datepicker1/

**Keyboard Support**
**Left**: Move focus to the previous day. Will move to the last day of the previous month, if the current day is the first day of a month.
**Right**: Move focus to the next day. Will move to the first day of the following month, if the current day is the last day of a month.
**Up**: Move focus to the same day of the previous week. Will wrap to the appropriate day in the previous month.
**Down**: Move focus to the same day of the following week. Will wrap to the appropriate day in the following month.
**PgUp**: Move focus to the same date of the previous month. If that date does not exist, focus is placed on the last day of the month.
**PgUp**: Move focus to the same date of the following month. If that date does not exist, focus is placed on the last day of the month.
**Ctrl+PgUp**: Move focus to the same date of the previous year. If that date does not exist (e.g leap year), focus is placed on the last day of the month.
**Ctrl+PgDn**: Move focus to the same date of the following year. If that date does not exist (e.g leap year), focus is placed on the last day of the month.
Home: Move to the first day of the month.
End: Move to the last day of the month
Tab: Navigate between calander grid and previous/next selection buttons
Enter/Space: Select date

**Example Markup**
ARIA 1.0: [aria-activedescendant]
ARIA 1.0: [aria-atomic]
ARIA 1.0: [aria-hidden]
ARIA 1.0: [aria-live]
ARIA 1.0: [aria-selected]
ARIA 1.0: [role="application"]
ARIA 1.0: [role="button"]
ARIA 1.0: [role="grid"]
ARIA 1.0: [role="gridcell"]
ARIA 1.0: [role="heading"]

**Comment by abhipanda** [comment]
@LouisMazel Is this scheduled for any release cause without accessibility features we cannot use it

**Comment by LouisMazel** [comment]
#102

I will released this soon in `2.0.0-rc7`(beta version)

**Comment by LouisMazel** [comment]
I released : https://github.com/chronotruck/vue-ctk-date-time-picker/releases/tag/2.0.0-rc7
