### ISSUE TITLE
Calendar doesn't change

### ISSUE THREAD

**Issue by Gansgar** [chronotruck/vue-ctk-date-time-picker#53]
I've tried to use this plugin by following the steps indicated in the UMD subsection of the Usage section in the readme. 

So my code imports Vue.js, the css and the js of this plugin. The calendar also pops-up when I click on the field and I can see and use everything, except clicking a date. In the Vue.js Dev Tools I can see that the "change-date" event is being fired, but the selected date will not change. Also the text field doesn't have anything in it except "Select date & time"

EDIT: I've not imported any other dependency of this library. But I thought that all of them are included in the 1.3mb big minified UMD js.

**Comment by LouisMazel** [comment]
Hi,

Have you set a `v-model` ?
Can you give me an example of code ? 

Thanks

**Comment by Gansgar** [comment]
That's how I use it:
```
<vue-ctk-date-time-picker></vue-ctk-date-time-picker>
```

**Comment by LouisMazel** [comment]
Here is an example that works: https://codepen.io/louismazel/pen/jQWNzQ

**Comment by Gansgar** [comment]
Wow yes thank you. That helped. Would be awesome if you could put the necessity for the `v-model` attribute into the README. I think that help a few developers who are just starting with Vue.js.
