### ISSUE TITLE
How to select Year

### ISSUE THREAD

**Issue by abdulcrb** [chronotruck/vue-ctk-date-time-picker#54]
How to select Year ? If i need to select year example 2021 
Thx

**Comment by LouisMazel** [comment]
Hi, 

It's not directly possible for now. you can just switch month by month. 
I add `enhancement` label for add this feature later. 

Thanks

**Comment by LouisMazel** [comment]
Hi,

I released a beta version with this feature (2.0.0-rc5)
You can test it :
npm install vue-ctk-date-time-picker@beta
DEMO : https://htmlpreview.github.io/?https://github.com/chronotruck/vue-ctk-date-time-picker/blob/feature/refont/demo/index.html
DOC : https://github.com/chronotruck/vue-ctk-date-time-picker/blob/feature/refont/README.md

Le me know if you have others feedbacks (events, bugs, etc)

Thanks

**Comment by LouisMazel** [comment]
How to select : 

![select year month](https://github.com/chronotruck/vue-ctk-date-time-picker/blob/feature/refont/assets/select-year-month.gif?raw=true)

**Comment by abdulcrb** [comment]
Ok Good Job. Thx for an update

**Comment by agriboz** [comment]
Links broken

**Comment by mapkbalaji** [comment]
When would this feature be added to the final build?
