### ISSUE TITLE
Please add types to make linters happy

### ISSUE THREAD

**Issue by MariMax** [chronotruck/vue-ctk-date-time-picker#55]
linter is not happy with
`import VueCtkDateTimePicker from 'vue-ctk-date-time-picker';`

Could not find a declaration file for module 'vue-ctk-date-time-picker'. 'node_modules/vue-ctk-date-time-picker/dist/vue-ctk-date-time-picker.min.js' implicitly has an 'any' type.
  Try `npm install @types/vue-ctk-date-time-picker` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-ctk-date-time-picker';`

**Comment by LouisMazel** [comment]
Incoming soon #68

**Comment by DanielShterenberg** [comment]
I can still reproduce the issue, unfortunately.
Tried to use 'npm install vue-ctk-date-time-picker' but it didn't help.

I'm using Webstorm 2019.
