### ISSUE TITLE
[Feature Request] Custom shortcuts

### ISSUE THREAD

**Issue by rajagopalx** [chronotruck/vue-ctk-date-time-picker#58]
First of all, Thanks for the very good DateTime range picker. Best responsive date range picker as fas as I seen in vuejs.

It's better to have custom shortcuts. So that we can write our own like Yesterday, Today, Last 2 months.

Thanks again.

**Comment by LouisMazel** [comment]
Hi,

I released a beta version with this feature (2.0.0-rc4)
You can test it :
npm install vue-ctk-date-time-picker@beta
DEMO : https://htmlpreview.github.io/?https://github.com/chronotruck/vue-ctk-date-time-picker/blob/feature/refont/demo/index.html
DOC : https://github.com/chronotruck/vue-ctk-date-time-picker/blob/feature/refont/README.md

Le me know if you have others feedbacks (events, bugs, etc)

Thanks
