### ISSUE TITLE
Protocol specific reference to Roboto font in vue-ctk-date-time-picker.vue

### ISSUE THREAD

**Issue by CrouchingMuppet** [chronotruck/vue-ctk-date-time-picker#61]
I'm not sure this font reference should even exist in the library.  If we don't have Roboto available on our site, shouldn't it just rely on a fallback.

In our specific case, the reference is actually causing a performance issue and I'm guessing it is as a result of protocol boundaries or possibly proxy/firewall.

It may help just to use a protocol relative reference, i.e:
@import url('//fonts.googleapis.com...

**Comment by LouisMazel** [comment]
Yes right, I'll fix it

Thanks
