### ISSUE TITLE
How to disable specific hours

### ISSUE THREAD

**Issue by askshinde** [chronotruck/vue-ctk-date-time-picker#63]
How to disable specific hours in <vue-ctk-date-time-picker>

**Comment by LouisMazel** [comment]
It's not possible for now
I add this feature on my backlogs

Thanks

**Comment by askshinde** [comment]
Got it right this time, I called the import statement inside the vue rather
than calling in the main app.js

Thank you

**Comment by LouisMazel** [comment]
In the next release you will can disable specific hours ! 
https://github.com/chronotruck/vue-ctk-date-time-picker/pull/68/commits/ba3df36c731b921bee53064e36ceefc17e425bb2

I release this soon
