### ISSUE TITLE
make datetime out of modal body, even click !

### ISSUE THREAD

**Issue by hasbycs** [chronotruck/vue-ctk-date-time-picker#73]

**Comment by LouisMazel** [comment]
I don't understand your feedback, can you give me some explanation ? 

Thanks

**Comment by LouisMazel** [comment]
I close this issue for now

**Comment by hasbycs** [comment]
![image](https://user-images.githubusercontent.com/26341603/50066711-fc1bc280-01ef-11e9-9cbf-0c96de28a8b8.png)
  
please help me to make datetimepicker out of modal

**Comment by slaponicus** [comment]
To solve this, my teammate and I just added `overflow: visible` to our modal elements (in our case, using Bulma, this was `modal-card` and `modal-card-body`).

**Comment by rickerp** [comment]
@slaponicus can you give a further explanation please

**Comment by Aterr** [comment]
This might be related to #262 
But there is no answer as well.
