### ISSUE TITLE
NuxtJS compatibility

### ISSUE THREAD

**Issue by WilliamDASILVA** [chronotruck/vue-ctk-date-time-picker#75]
Getting a `window is not defined` when using this plugin in a SSR environment (aka NuxtJS).
Would be great if this plugin is compatible with NuxtJS out of the box.

To fix this problem, you should be careful when using `window` and the `document` because they are not defined in the server-side.

You can learn more about this common issue here: https://fr.nuxtjs.org/faq/window-document-undefined/

Even using the <no-ssr> tags does not work properly:
```html
<no-ssr>
  <vue-ctk-date-time-picker />
</no-ssr>
```
https://fr.nuxtjs.org/api/components-no-ssr/

**Comment by LouisMazel** [comment]
#84
