### ISSUE TITLE
"This week" shortcut doesn't appear to be respecting locale

### ISSUE THREAD

**Issue by knackjason** [chronotruck/vue-ctk-date-time-picker#86]
It seems like the "this week" shortcut isn't respecting the locale. My locale is `en`. The calendar is starting on Sunday (which is correct) but when I select "this week", the past Monday - the following Sunday is selected. I expected it to select the previous Sunday - Saturday.

**Comment by LouisMazel** [comment]
Thanks for your feedback, I will fix this soon !

**Comment by knackjason** [comment]
Thanks for the quick turnaround!
