### ISSUE TITLE
without-input vs inline

### ISSUE THREAD

**Issue by knackjason** [chronotruck/vue-ctk-date-time-picker#87]
I'm a little confused about the `without-input` prop. I thought `:without-input="true"` would just show the picker UI w/o inserting an input element. It does seem to inline the UI but there's still an input element.

I eventually noticed the `inline` prop on your demo page, which produces the desired effect for me. However, `inline` is not listed in the README. 

So two suggestions:

1. Add an explanation about what `without-input` does. Maybe add a new column to your props table to add explanations for all the props?
2. Add `inline` to the README

**Comment by LouisMazel** [comment]
Hi, 

Thanks for your feedback. It's an error in the README/Doc. 
I will fix this !

**Comment by knackjason** [comment]
Thanks!
