### ISSUE TITLE
Chinese support

### ISSUE THREAD

**Issue by jobin-sun** [chronotruck/vue-ctk-date-time-picker#90]
I wan add Chinese support, but i can not find the language sheet, how to do?

**Comment by LouisMazel** [comment]
Hi,

You can set the locale attribut to `zh-cn`

![chinese](https://pouch.jumpshare.com/preview/R2N4BGMNMeNn-wK0_wjUqAbGrgFI_pgage8R-D_QxG2uajOJZtleWF35z7JKl2aANhPuQANK1x5MrlbpvlcCzFrWRC8tYABFuekS8mwDWCY)
