### ISSUE TITLE
Use npm typeface-roboto

### ISSUE THREAD

**Issue by knackjason** [chronotruck/vue-ctk-date-time-picker#98]
I was wondering if it would be possible to remove the `@import url('//fonts.googleapis.com/css?family=Roboto:400,500,700');` statement and use [typeface-roboto](https://www.npmjs.com/package/typeface-roboto) (or include the font as part of the build process).

The reason I ask is that while I develop my app while connected to the Internet, I deploy my app to a private corporate network without Internet access. The app fails to load properly because it can't connect to Google Fonts and I end up having to go in and manually remove the import statement.

If there's another way to get around this, I'd be happy to find out about it. Thanks!

**Comment by knackjason** [comment]
Some other options, if you prefer including Roboto in your distribution vs making it a dependency:

- https://www.npmjs.com/package/google-fonts-plugin
- https://www.npmjs.com/package/google-fonts-webpack-plugin

**Comment by LouisMazel** [comment]
Hi ! 

I will analyze this option and I will come back to you to tell you if I add this or not.

Thank you!

**Comment by knackjason** [comment]
I appreciate you looking into it, thanks!

**Comment by LouisMazel** [comment]
#101
I removed the font import
I will released this in '2.0.0-rc7` (beta version)

**Comment by LouisMazel** [comment]
I released : https://github.com/chronotruck/vue-ctk-date-time-picker/releases/tag/2.0.0-rc7

**Comment by knackjason** [comment]
Cool, thanks!
