### ISSUE TITLE
How to remove label

### ISSUE THREAD

**Issue by monkhsaikhan** [chronotruck/vue-ctk-date-time-picker#99]
Hello, I want remove label when date selected. Show just date. Help me

**Comment by LouisMazel** [comment]
Hello @monkhsaikhan, 

You can't for now. I released a beta version where you can use a custom element (input, button, etc) to trigger the component. 

Try this if you want. 
You have all info here : https://github.com/chronotruck/vue-ctk-date-time-picker/releases/tag/2.0.0-rc6

Thanks
